# ─── SonarCloud Project Config ────────────────────────────────
sonar.projectKey=ajaysan2017_AwareWallet
sonar.organization=ajaysan2017

# Project info
sonar.projectName=AwareWallet
sonar.projectVersion=1.0

# Source code location
sonar.sources=apps,aware_wallet
sonar.exclusions=**/migrations/**,**/venv/**,**/staticfiles/**,**/__pycache__/**

# Python specific
sonar.python.version=3.9

# Test coverage (optional for now)
sonar.python.coverage.reportPaths=coverage.xml