# Generated by Django 4.2.29 on 2026-03-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('icon', models.CharField(default='tag', help_text="Icon name e.g. 'food', 'car'", max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color e.g. #6366f1', max_length=7)),
                ('is_default', models.BooleanField(default=False, help_text='System default category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['type', 'name'],
            },
        ),
    ]
